# pubspec.yaml
name: sway
description: Find perfect hammock spots in Malta
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # State management
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  provider: ^6.0.5
  
  # Firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.3
  cloud_firestore: ^4.8.1
  
  # Maps and Location
  google_maps_flutter: ^2.2.8
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  permission_handler: ^10.2.0
  
  # UI components
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.2.3
  image_picker: ^0.8.9
  photo_view: ^0.14.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.5
  flutter_secure_storage: ^8.0.0



  
  # Networking
  dio: ^5.2.0
  json_annotation: ^4.8.1
  
  # Utilities
  shared_preferences: ^2.1.2
  intl: ^0.18.1
  url_launcher: ^6.1.11
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.1
  bloc_test: ^9.1.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700